### ISSUE TITLE
Begin Versioning of API endpoints

### ISSUE THREAD

**Issue by FraserTooth** [FraserTooth/japan_grid_carbon_api#18]
Current API routing is `/daily_carbon_intensity/...`

We should move to `/<versionNumber>/daily_carbon_intensity/`

Please start with a sensible starting point (v1, beta, etc. opinions welcome)

**Comment by DhrubojyotiBis1** [comment]
I would like to work on this issue. But I have a doubt, integrating `<versionNumber>` in the APIs will make the applications using the APIs more prone to break.

**Comment by FraserTooth** [comment]
@DhrubojyotiBis1 hello 👋
What would you suggest? 
Right now the API is definitely in a not-ready-for-consumption stage.
But I predict over time, post-beta, there may be larger changes to the API
I want to institute a versioning system for breaking changes, so older versions of the API can still support applications that use them. In this way, I feel it would be the opposite of what you suggest! Applications using a given version of the API will be able to continue using it without being forced to update.

**Comment by DhrubojyotiBis1** [comment]
> @DhrubojyotiBis1 hello 👋
> What would you suggest?
> Right now the API is definitely in a not-ready-for-consumption stage.
> But I predict over time, post-beta, there may be larger changes to the API
> I want to institute a versioning system for breaking changes, so older versions of the API can still support applications that use them. In this way, I feel it would be the opposite of what you suggest! Applications using a given version of the API will be able to continue using it without being forced to update.

Yes, I understand now. I will replace `/daily_carbon_intensity/...` with `/v0.1/daily_carbon_intensity/..` since it is a very early stage. What do you think?

**Comment by FraserTooth** [comment]
Sure that works. Thank you.
Please make a PR whenever you are ready. 
Do check the tests and update them if necessary.

**Comment by DhrubojyotiBis1** [comment]
Sure. Can you assign this issue to me?

**Comment by FraserTooth** [comment]
Done
